/**
 * DARASA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.CASA

/**
 * 
 * @param badgeId 
 * @param image 
 * @param year 
 * @param casaId 
 * @param casa 
 */
data class Badge (

    val badgeId: kotlin.Long? = null,
    val image: kotlin.ByteArray? = null,
    val year: kotlin.Int? = null,
    val casaId: kotlin.Long? = null,
    val casa: CASA? = null
) {
}