/**
 * DARASA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param casaId 
 * @param vat 
 * @param logo 
 */
data class CASA (

    val casaId: kotlin.Long? = null,
    val vat: kotlin.String? = null,
    val logo: kotlin.ByteArray? = null
) {
}