/**
 * DARASA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Enterprise

/**
 * 
 * @param enterpriseAdvertId 
 * @param enterpriseId 
 * @param image 
 * @param active 
 * @param enterprise 
 */
data class EnterpriseAdvert (

    val enterpriseAdvertId: kotlin.Long? = null,
    val enterpriseId: kotlin.Long? = null,
    val image: kotlin.ByteArray? = null,
    val active: kotlin.Boolean? = null,
    val enterprise: Enterprise? = null
) {
}