/**
 * DARASA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.EnterpriseAdvert
import io.swagger.client.models.Game
import io.swagger.client.models.GameEnterpriseAdvert

/**
 * 
 * @param gameEnterpriseAdvertAppearanceId 
 * @param gameEnterpriseAdvertId 
 * @param gameId 
 * @param enterpriseAdvertId 
 * @param dateShown 
 * @param game 
 * @param enterpriseAdvert 
 * @param gameEnterpriseAdvert 
 */
data class GameEnterpriseAdvertAppearance (

    val gameEnterpriseAdvertAppearanceId: kotlin.Long? = null,
    val gameEnterpriseAdvertId: kotlin.Long? = null,
    val gameId: kotlin.Long? = null,
    val enterpriseAdvertId: kotlin.Long? = null,
    val dateShown: java.time.LocalDateTime? = null,
    val game: Game? = null,
    val enterpriseAdvert: EnterpriseAdvert? = null,
    val gameEnterpriseAdvert: GameEnterpriseAdvert? = null
) {
}