/**
 * DARASA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.GameCompany

/**
 * 
 * @param gameId 
 * @param gameCompanyId 
 * @param active 
 * @param gameCompany 
 */
data class Game (

    val gameId: kotlin.Long? = null,
    val gameCompanyId: kotlin.Long? = null,
    val active: kotlin.Boolean? = null,
    val gameCompany: GameCompany? = null
) {
}