/**
 * DARASA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.CASAAdvert
import io.swagger.client.models.EnterpriseAdvert
import io.swagger.client.models.Game

/**
 * 
 * @param gameEnterpriseAdvertId 
 * @param gameId 
 * @param enterpriseAdvertId 
 * @param casaAdvertId 
 * @param date 
 * @param rank 
 * @param advertImage 
 * @param game 
 * @param enterpriseAdvert 
 * @param casaAdvert 
 */
data class GameEnterpriseAdvert (

    val gameEnterpriseAdvertId: kotlin.Long? = null,
    val gameId: kotlin.Long? = null,
    val enterpriseAdvertId: kotlin.Long? = null,
    val casaAdvertId: kotlin.Long? = null,
    val date: java.time.LocalDateTime? = null,
    val rank: kotlin.Long? = null,
    val advertImage: kotlin.ByteArray? = null,
    val game: Game? = null,
    val enterpriseAdvert: EnterpriseAdvert? = null,
    val casaAdvert: CASAAdvert? = null
) {
}