/**
 * DARASA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.CASA
import io.swagger.client.models.Enterprise
import io.swagger.client.models.GameCompany

/**
 * 
 * @param userId 
 * @param username 
 * @param name 
 * @param casaId 
 * @param gameCompanyId 
 * @param enterpriseId 
 * @param casa 
 * @param gameCompany 
 * @param enterprise 
 */
data class User (

    val userId: kotlin.Long? = null,
    val username: kotlin.String? = null,
    val name: kotlin.String? = null,
    val casaId: kotlin.Long? = null,
    val gameCompanyId: kotlin.Long? = null,
    val enterpriseId: kotlin.Long? = null,
    val casa: CASA? = null,
    val gameCompany: GameCompany? = null,
    val enterprise: Enterprise? = null
) {
}