//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class CASA: APIModel {

    public var casaId: Int?

    public var logo: File?

    public var vat: String?

    public init(casaId: Int? = nil, logo: File? = nil, vat: String? = nil) {
        self.casaId = casaId
        self.logo = logo
        self.vat = vat
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        casaId = try container.decodeIfPresent("casaId")
        logo = try container.decodeIfPresent("logo")
        vat = try container.decodeIfPresent("vat")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(casaId, forKey: "casaId")
        try container.encodeIfPresent(logo, forKey: "logo")
        try container.encodeIfPresent(vat, forKey: "vat")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? CASA else { return false }
      guard self.casaId == object.casaId else { return false }
      guard self.logo == object.logo else { return false }
      guard self.vat == object.vat else { return false }
      return true
    }

    public static func == (lhs: CASA, rhs: CASA) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
